<?php

namespace App\Controller;

use App\Entity\Presentation;
use App\Form\PresentationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class PresentationCreateController extends AbstractController
{
    /**
     * @Route("/admin/presentation", name="presentation")
     * @Route("/admin/{id}/presentation", name="presentation_edit")
     */
    public function presentationCreate(Presentation $presentation=null, Request $request, EntityManagerInterface $manager)
    {
        if(!$presentation){
            $presentation = new Presentation;
        }

        $form = $this->createForm(PresentationType::class, $presentation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($presentation->getFile() !== null){
                $fileName = $presentation->getFile();
                unlink("uploads/presentation/$fileName");
            }
            $file = $form['file']->getData();

            if ($file) {
                $newFileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

                try {
                    $file->move(
                        $this->getParameter('figuresImg_directory'),
                        $newFileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $presentation->setFile($newFileName);
            }

            $manager->persist($presentation);
            $manager->flush();

            $this->addFlash('success', 'Figure AJoutée/Modifiée avec succès !');

            return $this->redirectToRoute('home');
        }
        return $this->render('presentation/presentationCreate.html.twig', [
            'form' => $form->createView(),
            'editMode' => $presentation->getId() !== null,
            'newMode' => $presentation->getId() == null,
            'presentation' => $presentation,
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
